chore(navbar):create nav bar
andela/ah-kifaru-frontend pull request #14
Opened 2019-08-02 19:18 UTC by timi-codes

#### What does this PR do?
create app header
#### Description of Task to be completed?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?(if applicable)

#### Screenshots
[StoryID](url)

2019-08-06 07:36 UTC, Onyimatics approved these changes
Good job @timi-codes . Thanks for fixing the errors in the test and the other things you fixed.

2019-08-06 11:25 UTC, segunolalive reviewed
attend to the comments below. Good work.

2019-08-06 11:25 UTC, segunolalive commented on src/components/NavBar/index.js
> +        <a
Use React-router `Link` tag.

2019-08-06 21:56 UTC, olorunwalawrence commented on __test__/App.spec.js
> +    const wrapper = shallow(<App />);
kindly change the shallow method to mount as the TTL suggested

2019-08-07 01:58 UTC, kechyy approved these changes
@Good Job @timi-codes . I think I like the quality of your test. 

It looks good to me.

2019-08-07 10:44 UTC, codexempire approved these changes
👍 😄 🥇

2019-08-07 11:05 UTC, segunolalive requested changes
Good job

2019-08-07 11:05 UTC, segunolalive commented on src/components/NavBar/index.js
> +const AuthButtons = ({ isLoggedIn }) => {
```js
function AuthButtons ({ isLoggedIn = false }) => {
   if(isLoggedIn) { return null; }
   return ( // the rest of your code);
}

function AuthButtons ({ show = false }) => {
   return ( 
      show ? <your fragment here> : null
   );

  usage: <AuthButtons show={!isLoggedIn} />
}


```

2019-08-08 14:58 UTC, segunolalive reviewed
Looking good

2019-08-08 14:58 UTC, segunolalive commented on tailwind.config.js
> +      // => @media (max-width: 639px) { ... }
remove dead code (comments)

2019-08-13 14:26 UTC, tobechukwuobitube commented on package.json
> +      "pre-push": "npm test"
Thank you @timi-codes for adding the `pre-push` command. 👍

2019-08-13 14:35 UTC, tobechukwuobitube commented on src/assets/icons/index.js
> +};
Good job here for removing the dead code. 👍

2019-08-13 14:42 UTC, tobechukwuobitube commented on tailwind.config.js
> +// tailwind.config.js
Remove this dead code

2019-08-13 14:57 UTC, tohbay reviewed
Great efforts have been demonstrated in this PR. 
Kudos @timi-codes 👍 
Is there a review link where we can test out this PR?

2019-08-13 17:20 UTC, tobechukwuobitube commented on src/components/NavBar/NavBar.scss
> +  height: 55px;
I think you should use relative sizes like `em`, `rem` and `%`

2019-08-13 17:27 UTC, olorunwalawrence requested changes
![image](https://user-images.githubusercontent.com/44552263/62962583-1ba6d180-bdf7-11e9-8c5b-e259d87f7556.png)

I think the login and get started buttons should not be included in the mobile view of the header since they are being catered for in this PR: https://github.com/andela/ah-kifaru-frontend/pull/15 , kindly remove them, and I think the logo image should not be fixed kindly use some relative sizes e.g rem, em or percentage, the hamburger needs some right padding from  the edge of the view.

2019-08-14 11:08 UTC, merged