chore(mobileLanding):card
andela/ah-kifaru-frontend pull request #15
Opened 2019-08-03 15:06 UTC by olorunwalawrence

#### What does this PR do?
- create mobile action page
#### Description of Task to be completed?
- create mobile action page
- create desktop action page
#### Any background context you want to provide?

#### Screenshots
<img width="519" alt="Screenshot 2019-08-03 at 3 47 55 PM" src="https://user-images.githubusercontent.com/44552263/62413585-77f43f00-b608-11e9-9704-73e450399b68.png">

2019-08-06 09:15 UTC, Onyimatics approved these changes
Good job @olorunwalawrence .Looks good to me. I hope you have made the changes requested by TTL?

2019-08-07 00:58 UTC, timi-codes requested changes
Good Job @olorunwalawrence, However, I think you should rename the file and components. Registration gives the impression that only the signup button is on the page. Maybe you could try something around AuthMenu.

2019-08-07 01:47 UTC, kechyy approved these changes
Good Job @olorunwalawrence . Looking exactly like the mock up design.

2019-08-13 07:49 UTC, tolumide-ng requested changes
Great job @olorunwalawrence , please check my Reviews and rebase

2019-08-13 07:49 UTC, tolumide-ng commented on src/routes/AppRouter.js
> +import Card from '../components/registration/index';
you might want to remove index from the end of this so you can have something like `import Card from '../components/registration` instead

2019-08-13 07:49 UTC, tolumide-ng commented on src/routes/AppRouter.js
> +    <Route path="/card" exact component={Card} />
I am still unsure if this is the right way this should work, how does this component know it should be rendered when the screensize is small? and not render when the screen size is large

2019-08-13 07:49 UTC, tolumide-ng commented on src/components/registration/index.js
> +              type="submit"
`type` should be button and not `submit`, there is no form at the top and make a dummy link of where this should link to. Can we do the same thing for the get started button to?

2019-08-13 07:49 UTC, tolumide-ng commented on tests/reg.spec.js
> +    const wrapper = shallow(<Registration />);
Good job @olorunwalawrence , can we change this to `mount`? Use `shallow` when you are rendering a React component within the component that you are shallowing

2019-08-14 10:35 UTC, Onyimatics requested changes
Well-done @olorunwalawrence . I left some comments.

2019-08-14 10:35 UTC, Onyimatics commented on tests/auth.spec.js
> +import Auth from '../src/components/auth';
Please can you change this `Auth` to something like `AuthLogin`.

2019-08-14 10:35 UTC, Onyimatics commented on src/components/auth/index.js
> +              href="/login"
`Get started` should have a `signup` link and not `login`

2019-08-14 11:06 UTC, timi-codes approved these changes
Looks good to me! @olorunwalawrence

2019-08-14 11:13 UTC, merged